### ISSUE TITLE
java.lang.IllegalStateException: Server does not respond as TS3 server!

### ISSUE THREAD

**Issue by kill0rz** [galexrt/docker-jts3servermod#4]
I am getting this error when connecting from Docker image to TS3 Server:
```
teamspeakbot_1  | Botname: Unable to connect to Teamspeak 3 server at teamspeak!
teamspeakbot_1  | Botname: java.lang.IllegalStateException: Server does not respond as TS3 server!
teamspeakbot_1  | Botname: Reconnecting in 65 seconds...
```

Is this an error of the docker image?

**Comment by galexrt** [comment]
Which image version are you using? You can get the image version by running: `docker images quay.io/galexrt/sinusbot:latest` and/or if using the Docker image from Docker Hub `docker images galexrt/sinusbot:latest`.

**Comment by kill0rz** [comment]
I am using docker-compose and I pull the image in Dockerfile via `FROM galexrt/jts3servermod:latest`.

**Comment by galexrt** [comment]
@kill0rz Are you modifying the `galexrt/sinusbot:latest` Docker image in the `Dockerfile` you mentioned?
Are you also sure that the image is up to date (`docker pull galexrt/sinusbot:latest`)?

**Comment by kill0rz** [comment]
Well I am actually not using this sinusbot image (afaik sinusbot is for playing music, right?) I am talking about the jts3servermod-Image. I am not modifying anything, Image is up to date (pulled it today).

**Comment by galexrt** [comment]
@kill0rz Sorry, yes I meant `jts3servermod` image.
Why are you having in the Dockerfile the line `FROM galexrt/jts3servermod:latest` in it?
You can directly use this image without having to build another image first.

**Comment by kill0rz** [comment]
I did some tests, but you are right, its more meaningful to use the image as-is in docker-compose.yml
I tried using this option, but same behavior.
"teamspeak" is the name of the TS Server. Its running version 3.0.13.8

![image](https://user-images.githubusercontent.com/14353631/35927923-325a572c-0c2c-11e8-89ab-d8e7b2ba74a0.png)

**Comment by kill0rz** [comment]
I guess the compose file would be useful ;)

```
  teamspeak:
    build: './teamspeak/'
    volumes:
        - '../_data/teamspeak/:/data/'
    ports:
        - '9987:9987/udp'
        - '30033:30033'
        - '10011:10011'
        - '41144:41144'
    restart: always

  teamspeakbot:
    #build: './teamspeakbot/'
    image: galexrt/jts3servermod
    volumes:
        - './teamspeakbot/config/:/jts3servermod/config'
    restart: always
    depends_on:
      - 'teamspeak'
    ports:
        - 8087:8087
```
